baseURL       = 'https://brick.camp/'
locale        = 'en-us'
title         = 'brick.camp'
enableGitInfo = true

[build]
  noJSConfigInAssets = true
  [build.buildStats]
    enable = true

[[cascade]]
  [cascade.sitemap]
    disable = true
  [cascade.target]
    kind = '*'
    path = '{/data,/data/**,/parts,/parts/**}'
[[cascade]]
  [cascade.build]
    render = 'never'
  [cascade.target]
    kind = '{taxonomy,term}'
    path = '{/tags,/tags/**,/uses,/uses/**}'
[[cascade]]
  outputs = ["csv"]
  [cascade.target]
    kind = "{taxonomy,term}"
    path = '{/parts,/parts/**}'
[[cascade]]
  [cascade.build]
    render = 'never'
  [cascade.target]
    kind = "section"

[imaging]
  anchor = 'Center'
  bgColor = '#ffffff'
  compression = 'lossy'
  quality = 90
  resampleFilter = 'Lanczos'
  [imaging.webp]
    method = 6
    useSharpYuv = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.145.0"

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[params]
  dateFormat = 'Jan. 2, 2006'
  description = 'A visual dictionary of LEGO® building techniques'

[taxonomies]
  part = 'parts'
  uses = 'uses'
  tag  = 'tags'

[uglyURLs]
  _data = true