[LDView]
AllowPrimitiveSubstitution=1
AnisoLevel=1
AutoCrop=0
BFC=0
BackgroundColor3=16777215
BlackHighlights=0
CameraLocationLookAt=1
ConditionalHighlights=1
CurveQuality=12
EdgeThickness=1
EdgesOnly=0
ExamineMode=1
FOV=20
HiResPrimitives=1
JPGProgressive=0
JPGQuality=95
JPGSubSampling=2
KeepRightSideUp=1
LightVector="0.000000,0.000000,1.000000"
Lighting=1
LineSmoothing=1
NoLightGeom=0
OneLight=0
OptionalStandardLight=1
Poll=3
PolygonOffset=1
SaveActualSize=1
SaveAlpha=0
SaveDigits=3
SaveExportType=1
SaveHeight=800
SaveImageType=1
SaveSeries=0
SaveSteps=0
SaveWidth=800
SaveZoomToFit=0
SeamWidth=1
Seams=1
ShowAxes=0
ShowErrors\Error00=1
ShowErrors\Error01=1
ShowErrors\Error02=1
ShowErrors\Error03=1
ShowErrors\Error04=1
ShowErrors\Error05=1
ShowErrors\Error06=1
ShowErrors\Error07=1
ShowErrors\Error08=1
ShowErrors\Error09=1
ShowErrors\Error10=1
ShowErrors\Error11=1
ShowErrors\Error12=1
ShowErrors\Error13=1
ShowErrors\Error14=1
ShowErrors\Error15=1
ShowErrors\Error16=1
ShowErrors\Error17=1
ShowErrors\Error18=1
ShowHighlightLines=1
ShowWarnings=1
SortTransparent=1
SubduedLighting=1
TextureOffsetFactor=1
TextureStuds=0
TransDefaultColor=0
UseFlatShading=1
UseQualityLighting=1
UseQualityStuds=1
UseSpecular=1
UseStipple=0
ViewMode=0
